version: '2'

services:
  n1:
    image: orbs:export
    volumes:
      - ./logs/:/opt/orbs/logs
      - ./:/opt/orbs/config
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/n1.json --log /opt/orbs/logs/node1.log

  n2:
    image: orbs:export
    ports:
      - 8080:8080
    volumes:
      - ./logs/:/opt/orbs/logs
      - ./:/opt/orbs/config
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/n2.json --log /opt/orbs/logs/node2.log

  n3:
    image: orbs:export
    volumes:
      - ./logs/:/opt/orbs/logs
      - ./:/opt/orbs/config
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/n3.json --log /opt/orbs/logs/node3.log

  n4:
    image: orbs:export
    volumes:
      - ./logs/:/opt/orbs/logs
      - ./:/opt/orbs/config
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/n4.json --log /opt/orbs/logs/node4.log
  
  n5:
    image: orbs:export
    volumes:
      - ./logs/:/opt/orbs/logs
      - ./:/opt/orbs/config
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/n5.json --log /opt/orbs/logs/node5.log

  