version: '2'
services:
  control:
    container_name: jepsen-control
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    ports:
      - "8080"
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
  node:
    container_name: jepsen-node
    build: ./node
    env_file: ./secret/node.env
    privileged: true
  n1:
    extends: node
    container_name: jepsen-n1
    hostname: n1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  n2:
    extends: node
    container_name: jepsen-n2
    hostname: n2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  n3:
    extends: node
    container_name: jepsen-n3
    hostname: n3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  n4:
    extends: node
    container_name: jepsen-n4
    hostname: n4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  n5:
    extends: node
    container_name: jepsen-n5
    hostname: n5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
